// <auto-generated />
using System;
using Ihos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ihos.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425012959_AddCustomerTable")]
    partial class AddCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ihos.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ActionType");

                    b.HasIndex("ActorId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly?>("PreviousExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("PreviousInsurer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FullName");

                    b.HasIndex("FullName", "Phone", "CreatedBy")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ApprovedRows")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletionReason")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PendingRows")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("RejectedRows")
                        .HasColumnType("integer");

                    b.Property<int>("ResolvedRows")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.ImportRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MappingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PlanTypeMappingId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VehicleModelMappingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("MappingStatus");

                    b.HasIndex("PlanTypeMappingId");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("VehicleModelMappingId");

                    b.ToTable("import_records", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.InsuranceCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("insurance_companies", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BailBond")
                        .HasColumnType("numeric(15,2)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverageDetails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExcessAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ExternalPackageId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<decimal?>("FireTheft")
                        .HasColumnType("numeric(15,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxYear")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MedicalExpenses")
                        .HasColumnType("numeric(15,2)");

                    b.Property<int>("MinYear")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PassengerAccident")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("PersonalAccident")
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PremiumTotal")
                        .HasColumnType("numeric(15,2)");

                    b.Property<string>("RegionGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("RepairType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SourceBatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceImportRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("TpbiPerAccident")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("TpbiPerPerson")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("Tppd")
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("IsPublished");

                    b.HasIndex("SourceBatchId");

                    b.HasIndex("SourceImportRecordId");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("CompanyId", "VehicleModelId", "PlanType", "RepairType", "MinYear", "MaxYear", "SumInsured", "RegionGroup", "ExternalPackageId")
                        .IsUnique();

                    b.ToTable("insurance_plans", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.PlanTypeMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CanonicalPlanType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "RawName")
                        .IsUnique();

                    b.ToTable("plan_type_mappings", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("NameTh")
                        .IsUnique();

                    b.HasIndex("Region");

                    b.ToTable("provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEn = "Bangkok",
                            NameTh = "กรุงเทพมหานคร",
                            Region = "Bangkok"
                        },
                        new
                        {
                            Id = 2,
                            NameEn = "Nakhon Pathom",
                            NameTh = "นครปฐม",
                            Region = "Bangkok"
                        },
                        new
                        {
                            Id = 3,
                            NameEn = "Nonthaburi",
                            NameTh = "นนทบุรี",
                            Region = "Bangkok"
                        },
                        new
                        {
                            Id = 4,
                            NameEn = "Pathum Thani",
                            NameTh = "ปทุมธานี",
                            Region = "Bangkok"
                        },
                        new
                        {
                            Id = 5,
                            NameEn = "Samut Prakan",
                            NameTh = "สมุทรปราการ",
                            Region = "Bangkok"
                        },
                        new
                        {
                            Id = 6,
                            NameEn = "Kamphaeng Phet",
                            NameTh = "กำแพงเพชร",
                            Region = "North"
                        },
                        new
                        {
                            Id = 7,
                            NameEn = "Chiang Rai",
                            NameTh = "เชียงราย",
                            Region = "North"
                        },
                        new
                        {
                            Id = 8,
                            NameEn = "Chiang Mai",
                            NameTh = "เชียงใหม่",
                            Region = "North"
                        },
                        new
                        {
                            Id = 9,
                            NameEn = "Nan",
                            NameTh = "น่าน",
                            Region = "North"
                        },
                        new
                        {
                            Id = 10,
                            NameEn = "Phayao",
                            NameTh = "พะเยา",
                            Region = "North"
                        },
                        new
                        {
                            Id = 11,
                            NameEn = "Phichit",
                            NameTh = "พิจิตร",
                            Region = "North"
                        },
                        new
                        {
                            Id = 12,
                            NameEn = "Phitsanulok",
                            NameTh = "พิษณุโลก",
                            Region = "North"
                        },
                        new
                        {
                            Id = 13,
                            NameEn = "Phetchabun",
                            NameTh = "เพชรบูรณ์",
                            Region = "North"
                        },
                        new
                        {
                            Id = 14,
                            NameEn = "Phrae",
                            NameTh = "แพร่",
                            Region = "North"
                        },
                        new
                        {
                            Id = 15,
                            NameEn = "Mae Hong Son",
                            NameTh = "แม่ฮ่องสอน",
                            Region = "North"
                        },
                        new
                        {
                            Id = 16,
                            NameEn = "Lampang",
                            NameTh = "ลำปาง",
                            Region = "North"
                        },
                        new
                        {
                            Id = 17,
                            NameEn = "Lamphun",
                            NameTh = "ลำพูน",
                            Region = "North"
                        },
                        new
                        {
                            Id = 18,
                            NameEn = "Sukhothai",
                            NameTh = "สุโขทัย",
                            Region = "North"
                        },
                        new
                        {
                            Id = 19,
                            NameEn = "Uttaradit",
                            NameTh = "อุตรดิตถ์",
                            Region = "North"
                        },
                        new
                        {
                            Id = 20,
                            NameEn = "Chai Nat",
                            NameTh = "ชัยนาท",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 21,
                            NameEn = "Nakhon Nayok",
                            NameTh = "นครนายก",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 22,
                            NameEn = "Nakhon Sawan",
                            NameTh = "นครสวรรค์",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 23,
                            NameEn = "Phra Nakhon Si Ayutthaya",
                            NameTh = "พระนครศรีอยุธยา",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 24,
                            NameEn = "Lop Buri",
                            NameTh = "ลพบุรี",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 25,
                            NameEn = "Samut Songkhram",
                            NameTh = "สมุทรสงคราม",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 26,
                            NameEn = "Samut Sakhon",
                            NameTh = "สมุทรสาคร",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 27,
                            NameEn = "Sing Buri",
                            NameTh = "สิงห์บุรี",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 28,
                            NameEn = "Saraburi",
                            NameTh = "สระบุรี",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 29,
                            NameEn = "Suphan Buri",
                            NameTh = "สุพรรณบุรี",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 30,
                            NameEn = "Ang Thong",
                            NameTh = "อ่างทอง",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 31,
                            NameEn = "Uthai Thani",
                            NameTh = "อุทัยธานี",
                            Region = "Central"
                        },
                        new
                        {
                            Id = 32,
                            NameEn = "Kalasin",
                            NameTh = "กาฬสินธุ์",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 33,
                            NameEn = "Khon Kaen",
                            NameTh = "ขอนแก่น",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 34,
                            NameEn = "Chaiyaphum",
                            NameTh = "ชัยภูมิ",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 35,
                            NameEn = "Nakhon Phanom",
                            NameTh = "นครพนม",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 36,
                            NameEn = "Nakhon Ratchasima",
                            NameTh = "นครราชสีมา",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 37,
                            NameEn = "Bueng Kan",
                            NameTh = "บึงกาฬ",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 38,
                            NameEn = "Buri Ram",
                            NameTh = "บุรีรัมย์",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 39,
                            NameEn = "Maha Sarakham",
                            NameTh = "มหาสารคาม",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 40,
                            NameEn = "Mukdahan",
                            NameTh = "มุกดาหาร",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 41,
                            NameEn = "Yasothon",
                            NameTh = "ยโสธร",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 42,
                            NameEn = "Roi Et",
                            NameTh = "ร้อยเอ็ด",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 43,
                            NameEn = "Loei",
                            NameTh = "เลย",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 44,
                            NameEn = "Si Sa Ket",
                            NameTh = "ศรีสะเกษ",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 45,
                            NameEn = "Sakon Nakhon",
                            NameTh = "สกลนคร",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 46,
                            NameEn = "Surin",
                            NameTh = "สุรินทร์",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 47,
                            NameEn = "Nong Khai",
                            NameTh = "หนองคาย",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 48,
                            NameEn = "Nong Bua Lam Phu",
                            NameTh = "หนองบัวลำภู",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 49,
                            NameEn = "Amnat Charoen",
                            NameTh = "อำนาจเจริญ",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 50,
                            NameEn = "Udon Thani",
                            NameTh = "อุดรธานี",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 51,
                            NameEn = "Ubon Ratchathani",
                            NameTh = "อุบลราชธานี",
                            Region = "Northeast"
                        },
                        new
                        {
                            Id = 52,
                            NameEn = "Chanthaburi",
                            NameTh = "จันทบุรี",
                            Region = "East"
                        },
                        new
                        {
                            Id = 53,
                            NameEn = "Chachoengsao",
                            NameTh = "ฉะเชิงเทรา",
                            Region = "East"
                        },
                        new
                        {
                            Id = 54,
                            NameEn = "Chon Buri",
                            NameTh = "ชลบุรี",
                            Region = "East"
                        },
                        new
                        {
                            Id = 55,
                            NameEn = "Trat",
                            NameTh = "ตราด",
                            Region = "East"
                        },
                        new
                        {
                            Id = 56,
                            NameEn = "Prachin Buri",
                            NameTh = "ปราจีนบุรี",
                            Region = "East"
                        },
                        new
                        {
                            Id = 57,
                            NameEn = "Rayong",
                            NameTh = "ระยอง",
                            Region = "East"
                        },
                        new
                        {
                            Id = 58,
                            NameEn = "Sa Kaeo",
                            NameTh = "สระแก้ว",
                            Region = "East"
                        },
                        new
                        {
                            Id = 59,
                            NameEn = "Kanchanaburi",
                            NameTh = "กาญจนบุรี",
                            Region = "West"
                        },
                        new
                        {
                            Id = 60,
                            NameEn = "Tak",
                            NameTh = "ตาก",
                            Region = "West"
                        },
                        new
                        {
                            Id = 61,
                            NameEn = "Prachuap Khiri Khan",
                            NameTh = "ประจวบคีรีขันธ์",
                            Region = "West"
                        },
                        new
                        {
                            Id = 62,
                            NameEn = "Phetchaburi",
                            NameTh = "เพชรบุรี",
                            Region = "West"
                        },
                        new
                        {
                            Id = 63,
                            NameEn = "Ratchaburi",
                            NameTh = "ราชบุรี",
                            Region = "West"
                        },
                        new
                        {
                            Id = 64,
                            NameEn = "Krabi",
                            NameTh = "กระบี่",
                            Region = "South"
                        },
                        new
                        {
                            Id = 65,
                            NameEn = "Chumphon",
                            NameTh = "ชุมพร",
                            Region = "South"
                        },
                        new
                        {
                            Id = 66,
                            NameEn = "Trang",
                            NameTh = "ตรัง",
                            Region = "South"
                        },
                        new
                        {
                            Id = 67,
                            NameEn = "Nakhon Si Thammarat",
                            NameTh = "นครศรีธรรมราช",
                            Region = "South"
                        },
                        new
                        {
                            Id = 68,
                            NameEn = "Narathiwat",
                            NameTh = "นราธิวาส",
                            Region = "South"
                        },
                        new
                        {
                            Id = 69,
                            NameEn = "Pattani",
                            NameTh = "ปัตตานี",
                            Region = "South"
                        },
                        new
                        {
                            Id = 70,
                            NameEn = "Phang Nga",
                            NameTh = "พังงา",
                            Region = "South"
                        },
                        new
                        {
                            Id = 71,
                            NameEn = "Phatthalung",
                            NameTh = "พัทลุง",
                            Region = "South"
                        },
                        new
                        {
                            Id = 72,
                            NameEn = "Phuket",
                            NameTh = "ภูเก็ต",
                            Region = "South"
                        },
                        new
                        {
                            Id = 73,
                            NameEn = "Ranong",
                            NameTh = "ระนอง",
                            Region = "South"
                        },
                        new
                        {
                            Id = 74,
                            NameEn = "Songkhla",
                            NameTh = "สงขลา",
                            Region = "South"
                        },
                        new
                        {
                            Id = 75,
                            NameEn = "Satun",
                            NameTh = "สตูล",
                            Region = "South"
                        },
                        new
                        {
                            Id = 76,
                            NameEn = "Surat Thani",
                            NameTh = "สุราษฎร์ธานี",
                            Region = "South"
                        },
                        new
                        {
                            Id = 77,
                            NameEn = "Yala",
                            NameTh = "ยะลา",
                            Region = "South"
                        });
                });

            modelBuilder.Entity("Ihos.Domain.Entities.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanId2")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanId3")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PremiumAtGeneration")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("PremiumAtGeneration2")
                        .HasColumnType("numeric(15,2)");

                    b.Property<decimal?>("PremiumAtGeneration3")
                        .HasColumnType("numeric(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("VehicleModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VehicleRegistration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VehicleYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("PlanId");

                    b.HasIndex("PlanId2");

                    b.HasIndex("PlanId3");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("InviteExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InviteTokenHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vehicle_makes", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleMarketValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionYear");

                    b.HasIndex("VehicleModelId");

                    b.HasIndex("VehicleModelId", "ProductionYear")
                        .IsUnique();

                    b.ToTable("vehicle_market_values", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EngineCC")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GearType")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MakeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.HasIndex("MakeId", "Name", "SubModel", "GearType")
                        .IsUnique();

                    b.ToTable("vehicle_models", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleModelMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CanonicalModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAutoSuggested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalModelId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "RawName")
                        .IsUnique();

                    b.ToTable("vehicle_model_mappings", (string)null);
                });

            modelBuilder.Entity("Ihos.Domain.Entities.ImportBatch", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.InsuranceCompany", "Company")
                        .WithMany("ImportBatches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.ImportRecord", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.ImportBatch", "Batch")
                        .WithMany("Records")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ihos.Domain.Entities.PlanTypeMapping", "PlanTypeMapping")
                        .WithMany()
                        .HasForeignKey("PlanTypeMappingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ihos.Domain.Entities.VehicleModelMapping", "VehicleModelMapping")
                        .WithMany()
                        .HasForeignKey("VehicleModelMappingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("PlanTypeMapping");

                    b.Navigation("VehicleModelMapping");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.InsurancePlan", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.InsuranceCompany", "Company")
                        .WithMany("InsurancePlans")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ihos.Domain.Entities.ImportBatch", "SourceBatch")
                        .WithMany()
                        .HasForeignKey("SourceBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ihos.Domain.Entities.ImportRecord", "SourceImportRecord")
                        .WithMany()
                        .HasForeignKey("SourceImportRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ihos.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("InsurancePlans")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("SourceBatch");

                    b.Navigation("SourceImportRecord");

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.PlanTypeMapping", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.InsuranceCompany", "Company")
                        .WithMany("PlanTypeMappings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.InsurancePlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ihos.Domain.Entities.InsurancePlan", "Plan2")
                        .WithMany()
                        .HasForeignKey("PlanId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ihos.Domain.Entities.InsurancePlan", "Plan3")
                        .WithMany()
                        .HasForeignKey("PlanId3")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plan");

                    b.Navigation("Plan2");

                    b.Navigation("Plan3");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleMarketValue", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.VehicleModel", "VehicleModel")
                        .WithMany("MarketValues")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleModel", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.VehicleMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleModelMapping", b =>
                {
                    b.HasOne("Ihos.Domain.Entities.VehicleModel", "CanonicalModel")
                        .WithMany("Mappings")
                        .HasForeignKey("CanonicalModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ihos.Domain.Entities.InsuranceCompany", "Company")
                        .WithMany("VehicleModelMappings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalModel");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.InsuranceCompany", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("InsurancePlans");

                    b.Navigation("PlanTypeMappings");

                    b.Navigation("VehicleModelMappings");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleMake", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Ihos.Domain.Entities.VehicleModel", b =>
                {
                    b.Navigation("InsurancePlans");

                    b.Navigation("Mappings");

                    b.Navigation("MarketValues");
                });
#pragma warning restore 612, 618
        }
    }
}
